swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger Rest Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /events:
    get:
      operationId: events.read_all
      tags:
        - Events
      summary: Read the entire set of events, sorted by furthest first
      description: Read the entire set of events, sorted by furthest first
      responses:
        200:
          description: Successfully read events set operation
          schema:
            type: array
            items:
              properties:
                event_id:
                  type: integer
                  description: Id of the event
                event_name:
                  type: string
                  description: Name of the event
                event_description:
                  type: string
                  description: Description of the event
                event_date:
                  type: string
                  description: Date of the event in word format
                event_start:
                  type: string
                  description: Start time of event
                event_end:
                  type: string
                  description: End time of event
                event_going:
                  type: integer
                  description: Number going to event
                event_interested:
                  type: integer
                  description: Number interested in event
                event_status:
                  type: string
                  description: Whether event is past, upcoming or live

  /events/{event_id}:
    get:
      operationId: events.read_one
      tags:
        - Events
      summary: Read one event
      description: Read one event
      parameters:
        - name: event_id
          in: path
          description: Id of the event to get
          type: integer
          required: True
      responses:
        200:
          description: Successfully read event from event data operation
          schema:
            type: object
            properties:
              event_id:
                type: integer
                description: Id of the event
              event_name:
                type: string
                description: Name of the event
              event_description:
                type: string
                description: Description of the event
              event_date:
                type: string
                description: Date of the event in word format
              event_start:
                type: string
                description: Start time of event
              event_end:
                type: string
                description: End time of event
              event_going:
                type: integer
                description: Number going to event
              event_interested:
                type: integer
                description: Number interested in event
              event_status:
                type: string
                description: Whether event is past, upcoming or live
    
  /events/upcoming:
    get:
      operationId: events.upcoming
      tags:
        - Events
      summary: Read the set of upcoming events, sorted by closest first
      description: Read the set of upcoming events, sorted by closest first
      responses:
        200:
          description: Successfully read events set operation
          schema:
            type: array
            items:
              properties:
                event_id:
                  type: integer
                  description: Id of the event
                event_name:
                  type: string
                  description: Name of the event
                event_description:
                  type: string
                  description: Description of the event
                event_date:
                  type: string
                  description: Date of the event in word format
                event_start:
                  type: string
                  description: Start time of event
                event_end:
                  type: string
                  description: End time of event
                event_going:
                  type: integer
                  description: Number going to event
                event_interested:
                  type: integer
                  description: Number interested in event
                event_status:
                  type: string
                  description: Whether event is past, upcoming or live

  /events/next:
    get:
      operationId: events.next
      tags:
        - Events
      summary: Read the next event
      description: Read the next event
      responses:
        200:
          description: Successfully read next event
          schema:
            type: array
            items:
              properties:
                event_id:
                  type: integer
                  description: Id of the event
                event_name:
                  type: string
                  description: Name of the event
                event_description:
                  type: string
                  description: Description of the event
                event_date:
                  type: string
                  description: Date of the event in word format
                event_start:
                  type: string
                  description: Start time of event
                event_end:
                  type: string
                  description: End time of event
                event_going:
                  type: integer
                  description: Number going to event
                event_interested:
                  type: integer
                  description: Number interested in event
                event_status:
                  type: string
                  description: Whether event is past, upcoming or live
            